# Generated by Django 6.0.2 on 2026-02-04 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='KpiTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi', models.CharField(max_length=100)),
                ('tahun', models.IntegerField()),
                ('jan_01', models.IntegerField(default=0)),
                ('feb_02', models.IntegerField(default=0)),
                ('mar_03', models.IntegerField(default=0)),
                ('apr_04', models.IntegerField(default=0)),
                ('may_05', models.IntegerField(default=0)),
                ('jun_06', models.IntegerField(default=0)),
                ('jul_07', models.IntegerField(default=0)),
                ('aug_08', models.IntegerField(default=0)),
                ('sep_09', models.IntegerField(default=0)),
                ('oct_10', models.IntegerField(default=0)),
                ('nov_11', models.IntegerField(default=0)),
                ('des_12', models.IntegerField(default=0)),
                ('setahun', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.company')),
            ],
        ),
    ]
