# Generated by Django 6.0.2 on 2026-02-06 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ManyToManyField(related_name='users', to='kpi.company')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='KpiTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi', models.CharField(max_length=100)),
                ('tahun', models.IntegerField()),
                ('jan_01', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('feb_02', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('mar_03', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('apr_04', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('may_05', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('jun_06', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('jul_07', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('aug_08', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sep_09', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('oct_10', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('nov_11', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('des_12', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('setahun', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('note', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='kpi.company')),
            ],
        ),
    ]
