# Generated by Django 6.0.2 on 2026-02-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.JSONField(default=list),
        ),
    ]
