# Generated by Django 6.0.2 on 2026-02-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_remove_user_company_user_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
            ],
            options={
                'db_table': 'company_user',
                'unique_together': {('user_id', 'company_id')},
            },
        ),
    ]
