# Generated by Django 6.0.2 on 2026-02-12 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_companyuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyuser',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='kpitarget',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
