# Generated by Django 6.0.2 on 2026-02-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_alter_kpitarget_apr_04_alter_kpitarget_aug_08_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpitarget',
            name='setahun',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
    ]
