# Generated by Django 6.0.2 on 2026-02-12 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0004_alter_companyuser_options_alter_kpitarget_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kpitarget',
            table='kpi_target',
        ),
    ]
